version: '3.8'

services:
  # Base de datos PostgreSQL (compartida para Next.js y Go Relayer)
  postgres:
    image: postgres:15-alpine
    container_name: kukuxumusu-postgres
    environment:
      POSTGRES_DB: kukuxumusu
      POSTGRES_USER: kukuxumusu
      POSTGRES_PASSWORD: kukuxumusu_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init-databases.sql:/docker-entrypoint-initdb.d/init-databases.sql
    networks:
      - kukuxumusu-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kukuxumusu -d kukuxumusu"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis para cache y sesiones
  redis:
    image: redis:7-alpine
    container_name: kukuxumusu-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - kukuxumusu-network
    command: redis-server --appendonly yes

  # Worker Node.js (Event Listener + Mint Executor + API Server)
  worker:
    build:
      context: .
      dockerfile: worker/Dockerfile
    container_name: kukuxumusu-worker
    ports:
      - "8082:8080"
    environment:
      - NODE_ENV=development
      - WORKER_PORT=8080
      - DATABASE_URL=postgres://kukuxumusu:kukuxumusu_dev@postgres:5432/kukuxumusu?sslmode=disable
      - REDIS_URL=redis://redis:6379
      # Blockchain - Base Sepolia
      - BASE_RPC_URL=https://sepolia.base.org
      - PAYMENT_CONTRACT_ADDRESS=0xa04cEda1fc7eeB2559d2C3936cA678D91b4530E3
      # Blockchain - Story Protocol
      - STORY_RPC_URL=https://rpc.odyssey.storyrpc.io
      - NFT_FACTORY_ADDRESS=0x75bf7b1DD6b3a666F18c7784B78871C429E92C71
      - NFT_CONTRACT_ADDRESS=0xd9b3913250035D6a2621Cefc9574f7F8c6e5F2B7
      # Trusted Signer (CRITICAL)
      - TRUSTED_SIGNER_PRIVATE_KEY=0xef0874b7f213a1c14f5dfa4f018d4224aa321ebc1dc87e9598ca8cc3602b131b
      # Relayer Private Key (for minting)
      - RELAYER_PRIVATE_KEY=0xef0874b7f213a1c14f5dfa4f018d4224aa321ebc1dc87e9598ca8cc3602b131b
      # IPFS/Pinata
      - PINATA_API_KEY=6f1d779a3d365e473914
      - PINATA_SECRET=b09e9d6d51dd3f336aa07ef1294c9fec88adf43430cb4474776706a61e629afc
      - PINATA_JWT=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySW5mb3JtYXRpb24iOnsiaWQiOiJlZjc1Y2E4NC1iMjUyLTRlODItYThmNy1mYzg5NWUyODkwNmYiLCJlbWFpbCI6InNtaWFzQHZvdHR1bi5jb20iLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwicGluX3BvbGljeSI6eyJyZWdpb25zIjpbeyJkZXNpcmVkUmVwbGljYXRpb25Db3VudCI6MSwiaWQiOiJGUkExIn0seyJkZXNpcmVkUmVwbGljYXRpb25Db3VudCI6MSwiaWQiOiJOWUMxIn1dLCJ2ZXJzaW9uIjoxfSwibWZhX2VuYWJsZWQiOmZhbHNlLCJzdGF0dXMiOiJBQ1RJVkUifSwiYXV0aGVudGljYXRpb25UeXBlIjoic2NvcGVkS2V5Iiwic2NvcGVkS2V5S2V5IjoiNmYxZDc3OWEzZDM2NWU0NzM5MTQiLCJzY29wZWRLZXlTZWNyZXQiOiJiMDllOWQ2ZDUxZGQzZjMzNmFhMDdlZjEyOTRjOWZlYzg4YWRmNDM0MzBjYjQ0NzQ3NzY3MDZhNjFlNjI5YWZjIiwiZXhwIjoxNzkwOTU3NDkxfQ.0JJWvYU5gnpNzlZt6Rq4GLpwfVX17i0P46DfgZGDI84
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - kukuxumusu-network
    restart: unless-stopped

  # Adminer para administrar la base de datos (opcional)
  adminer:
    image: adminer:latest
    container_name: kukuxumusu-adminer
    ports:
      - "8081:8080"
    depends_on:
      - postgres
    networks:
      - kukuxumusu-network

volumes:
  postgres_data:
  redis_data:

networks:
  kukuxumusu-network:
    driver: bridge
