version: '3.8'

services:
  # Base de datos PostgreSQL (compartida para Next.js y Go Relayer)
  postgres:
    image: postgres:15-alpine
    container_name: kukuxumusu-postgres
    environment:
      POSTGRES_DB: kukuxumusu
      POSTGRES_USER: kukuxumusu
      POSTGRES_PASSWORD: kukuxumusu_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init-databases.sql:/docker-entrypoint-initdb.d/init-databases.sql
    networks:
      - kukuxumusu-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kukuxumusu -d kukuxumusu"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis para cache y sesiones
  redis:
    image: redis:7-alpine
    container_name: kukuxumusu-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - kukuxumusu-network
    command: redis-server --appendonly yes

  # Worker Node.js (Event Listener + Mint Executor)
  worker:
    build:
      context: .
      dockerfile: worker/Dockerfile
    container_name: kukuxumusu-worker
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgres://kukuxumusu:kukuxumusu_dev@postgres:5432/kukuxumusu?sslmode=disable
      - REDIS_URL=redis://redis:6379
      - NEXT_PUBLIC_BASE_RPC_URL=${NEXT_PUBLIC_BASE_RPC_URL}
      - NEXT_PUBLIC_STORY_RPC_URL=${NEXT_PUBLIC_STORY_RPC_URL}
      - NEXT_PUBLIC_PAYMENT_CONTRACT_ADDRESS=${NEXT_PUBLIC_PAYMENT_CONTRACT_ADDRESS}
      - NEXT_PUBLIC_NFT_CONTRACT_ADDRESS=${NEXT_PUBLIC_NFT_CONTRACT_ADDRESS}
      - RELAYER_PRIVATE_KEY=${RELAYER_PRIVATE_KEY}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - kukuxumusu-network
    restart: unless-stopped

  # Adminer para administrar la base de datos (opcional)
  adminer:
    image: adminer:latest
    container_name: kukuxumusu-adminer
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - kukuxumusu-network

volumes:
  postgres_data:
  redis_data:

networks:
  kukuxumusu-network:
    driver: bridge
